baseURL = "https://saej.in"
languageCode = "en-us"
title = "Peter Villano's Personal Site"
theme = "LeftBeef"
publishDir = "docs"
cleanDestinationDir = true
enableEmoji = true
#enableRobotsTXT = true
timeZone = "America/Indiana/Indianapolis"