baseURL = "https://saej.in"
languageCode = "en-us"
title = "Peter Villano"
theme = "LeftBeef"
publishDir = "docs"
cleanDestinationDir = true
enableEmoji = true
#enableRobotsTXT = true
timeZone = "America/Indiana/Indianapolis"

[markup]
    [markup.highlight]
        codeFences = false

[menus]
    [[menus.main]]
        name = 'Resume'
        url = '/resume.html'
        post = ' (<a href="/peter-villano-resume.pdf">pdf</a>)'
        weight = 10
